language: python
python:
  - "2.6"
  - "2.7"
env:
    - DJANGO_SETTINGS_MODULE="dcuolfg.settings.common"
install:
    - pip install -r requirements.txt
    - python setup.py install
script: django-admin.py test
